
app_identifier "com.jagonzalr.Suggestion"
username "jagonzalr@gmail.com"

copyright "#{Time.now.year} José Antonio González Rodríguez"
app_icon './iTunesArtwork@2x.png'
app_rating_config_path './fastlane/rating_config.json'
price_tier 0
