
fastlane_version "1.83.0"

default_platform :ios

platform :ios do

  desc "Deploy a new version to the App Store"
  lane :appstore do
    build
    deliver(
        skip_binary_upload: false,
        skip_screenshots: true,
        skip_metadata: true,
        force: true
    )
  end

  desc "Uploads the metadata of the app"
  lane :metadata do
    deliver(
      skip_binary_upload: true,
      skip_screenshots: true,
      skip_metadata: false,
      force: true
    )
  end

  desc "Updates profiles"
  lane :profiles do
    match(type: "development")
    match(type: "appstore")
  end

  desc "Create screenshots and upload them"
  lane :screenshots do
    snapshot
    frameit
    sh "bash ./noFrame.sh"
    deliver(
      skip_binary_upload: true,
      skip_screenshots: false,
      skip_metadata: true,
      force: true
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :testflight do
    build
    pilot(
        ipa: "./fastlane/build/Suggestion.ipa",
    )
  end

  desc "Build the app"
  private_lane :build do
    match(type: "appstore")
    gym(scheme: "Suggestion")
  end

end
