
devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPhone 4s",
#   "iPad Retina",
#   "iPad Pro"
])

languages([
  "en-US"
  # "de-DE",
  # "it-IT",
  # ["pt", "pt_BR"]
])

scheme "Suggestion"
output_directory "./fastlane/screenshots"
clear_previous_screenshots true
workspace "./Suggestion.xcworkspace"
skip_open_summary true
reinstall_app true
